### ISSUE TITLE
Buttons remain light gray on OSX (Gimp 2.8.18)

### ISSUE THREAD

**Issue by gioloi** [draekko/gimp-cc-themes#2]
First, awesome work and themes.
Just installed Gimp 2.8.18 on OSX (El Capitan) and applied your themes.
Some elements of the ui remain light gray so text is unreadable. Also, some labels are dark as the background so they are invisible. See screenshot.
My mistake installing? Can I edit something in theme files to make it work?
The problem is related to the version of OS X? Or it is related to the latest version of GIMP?
Thank you in advance.

![gimp_dark_issues](https://cloud.githubusercontent.com/assets/7725900/17367332/d89610b4-598f-11e6-934d-8ed8e9a0905b.png)

**Comment by draekko** [comment]
Thank you. I have stopped maintaining this theme, i no longer use GIMP 2.8. All my current work is for GIMP 2.9+ (the future 2.10) and those related themes are already included there. Since i don't have access to a Mac these days so i can't say for sure why that would be an issue or what it could be. I doubt its an installation issue. If you can manage to get it working do a pull request and i will try merging back it in and add a credits section to the readme file listing you.

**Comment by gioloi** [comment]
Thank you. If I find a bit 'of time, I will try to solve the problem. I think that something has changed on the latest versions of GIMP 2.8, because other themes from the internet that worked well on (for example) 2.8.4 now does not work, with similar problems. Thank you again.

**Comment by draekko** [comment]
I installed 2.8.18 from my Linux distro and was unable to see those issues here so it's really some issue with the packaged Mac version most likely due to the gtk libraries packaged with it.

**Comment by draekko** [comment]
I've backported the GIMP 2.9.2 themes i did to use with 2.8.18 and above. Hopefully this works out better for you as they were tested on Mac at the time.

**Comment by draekko** [comment]
Coincidentally those themes were based of gimp cc themes originally :)

**Comment by gioloi** [comment]
Working perfect now! Thank you!

**Comment by draekko** [comment]
Glad it's resolved. Have a great week.
